-- نفّذ مرة واحدة. تجاهل خطأ Duplicate column name

ALTER TABLE Clients ADD COLUMN FirstName VARCHAR(100) NULL;
ALTER TABLE Clients ADD COLUMN LastName VARCHAR(100) NULL;
ALTER TABLE Clients ADD COLUMN DisplayName VARCHAR(150) NULL;
ALTER TABLE Clients ADD COLUMN Title VARCHAR(50) NULL;
ALTER TABLE Clients ADD COLUMN FatherName VARCHAR(100) NULL;
ALTER TABLE Clients ADD COLUMN MotherName VARCHAR(100) NULL;
ALTER TABLE Clients ADD COLUMN Gender VARCHAR(20) NULL;
ALTER TABLE Clients ADD COLUMN BirthDate DATETIME NULL;
ALTER TABLE Clients ADD COLUMN BirthPlace VARCHAR(100) NULL;
ALTER TABLE Clients ADD COLUMN City VARCHAR(100) NULL;
ALTER TABLE Clients ADD COLUMN Area VARCHAR(100) NULL;
ALTER TABLE Clients ADD COLUMN Street VARCHAR(150) NULL;
ALTER TABLE Clients ADD COLUMN Apartment VARCHAR(50) NULL;
ALTER TABLE Clients ADD COLUMN ContractNumber VARCHAR(50) NULL;
ALTER TABLE Clients ADD COLUMN Notes TEXT NULL;
ALTER TABLE Clients ADD COLUMN PaymentStatus VARCHAR(50) DEFAULT 'Pending';
ALTER TABLE Clients ADD COLUMN SecondaryPhone VARCHAR(30) NULL;
ALTER TABLE Clients ADD COLUMN IdFrontImage LONGTEXT NULL;
ALTER TABLE Clients ADD COLUMN IdBackImage LONGTEXT NULL;
ALTER TABLE Clients ADD COLUMN ContractFrontImage LONGTEXT NULL;
ALTER TABLE Clients ADD COLUMN ContractBackImage LONGTEXT NULL;
ALTER TABLE Clients ADD COLUMN HasFreeSubscription TINYINT(1) DEFAULT 0;
ALTER TABLE Clients ADD COLUMN FreeSpeed VARCHAR(50) NULL;
