sql {
    driver = "rlm_sql_mysql"
    server = "isp_mysql"
    port = 3306
    login = "isp_user"
    password = "SecureP@ssw0rd2026!"
    radius_db = "isp_system"
    $INCLUDE ${modconfdir}/${.:name}/main/${dialect}/queries.conf
}