client localhost {
    ipaddr = 127.0.0.1
    secret = Sham@mm@r!1993#Riad#1991
    shortname = localhost
    require_message_authenticator = no
}

client localhost_ipv6 {
    ipv6addr = ::1
    secret = Sham@mm@r!1993#Riad#1991
    shortname = localhost6
    require_message_authenticator = no
}

client all_networks {
    ipaddr = 0.0.0.0/0
    secret = Sham@mm@r!1993#Riad#1991
    shortname = all
    require_message_authenticator = no
    nas_type = other
}